[package]
name = "amm_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "amm_demo"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"

[features]
no-entrypoint = []
